"""empty message

Revision ID: 03d19f7e57c1
Revises: 
Create Date: 2020-04-01 11:07:16.764029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d19f7e57c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba-ws-search_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('search_field', sa.Text(), nullable=True),
    sa.Column('datetime_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author'),
    sa.UniqueConstraint('search_field')
    )
    op.create_table('nba-ws-tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('tweet_text', sa.String(), nullable=True),
    sa.Column('tweet_date', sa.DateTime(), nullable=True),
    sa.Column('json_data', sa.Text(), nullable=True),
    sa.Column('search_params', sa.Text(), nullable=True),
    sa.Column('datetime_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nba-ws-tweet')
    op.drop_table('nba-ws-search_field')
    # ### end Alembic commands ###
