"""Added new Model for search fields

Revision ID: 5488b1d394df
Revises: 
Create Date: 2020-02-18 16:15:46.342929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5488b1d394df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nba-ws-searchfield')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba-ws-searchfield',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('search_field', sa.TEXT(), nullable=True),
    sa.Column('datetime_added', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_field')
    )
    # ### end Alembic commands ###
