"""empty message

Revision ID: 8483b620d52c
Revises: 
Create Date: 2020-04-02 00:23:55.507314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8483b620d52c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba-ws-search_field',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('search_field', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datetime_added', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author'),
    sa.UniqueConstraint('search_field')
    )
    op.create_table('nba-ws-tweet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('tweet_text', sa.String(), nullable=True),
    sa.Column('tweet_date', sa.DateTime(), nullable=True),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datetime_added', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nba-ws-tweet')
    op.drop_table('nba-ws-search_field')
    # ### end Alembic commands ###
