"""Added model for Tweets

Revision ID: b97ca8a73993
Revises: 
Create Date: 2020-02-08 11:23:05.756825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97ca8a73993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nba-news-tweet', sa.Column('author_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nba-news-tweet', 'author_id')
    # ### end Alembic commands ###
